### ISSUE TITLE
Ubuntu:cannot get security labeling handle: No such file or directory

### ISSUE THREAD

**Issue by Flyfish233** [YadominJinta/atilo#1]
Flyme 6，ARM 64，apt install aptitude.

The following packages will be upgraded:             perl-base
1 upgraded, 27 newly installed, 0 to remove and 6 not upgraded.  
Need to get 0 B/10.2 MB of archives.        
After this operation, 53.3 MB of additional disk space will be used.
Do you want to continue? [Y/n] y            
dpkg: error processing archive /var/cache/apt/archives/perl-base_5.22.19ubuntu0.3_arm64.deb (--unpack):                                             
cannot get security labeling handle: No such file or directory
Errors were encountered while processing:         
E: Sub-process /usr/bin/dpkg returned an error code (1)

经查可能是 SElinux 问题，在 Linux_Delopy 应用中也有发生。

**Comment by YadominJinta** [comment]
找到了这样一篇
https://blog.csdn.net/ONE_SIX_MIX/article/details/52205341
