### ISSUE TITLE
E: Unable to locate package atilo

### ISSUE THREAD

**Issue by ghost** [YadominJinta/atilo#100]
✘  /data/data/com.termux/files/usr/etc/apt  echo "deb [trusted=yes arch=all] https://yadominjinta.github.io/files/ termux extras" >> $PREFIX/etc/apt/sources.list
 /data/data/com.termux/files/usr/etc/apt  pkg install atilo      Checking availability of current mirror: bad                      Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package atilo

**Comment by ghost** [comment]
All packages are up to date.
N: Skipping acquire of configured file 'extras/binary-aarch64/Packages' as repository 'https://yadominjinta.github.io/files termux InRelease' doesn't support architecture 'aarch64'

**Comment by ghost** [comment]
$ echo "deb [trusted=yes arch=all] https://yadominjinta.github.io/files/ termux extras" >> $PREFIX/etc/apt/sources.list
$ pkg in atilo
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: bad
[*] https://termux.mentality.rip/termux-packages-24: bad
Picking mirror: https://dl.bintray.com/termux/termux-packages-24
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package atilo
$

**Comment by MKamaitachi** [comment]
[](https://github.com/YadominJinta/atilo/issues/101)

**Comment by MKamaitachi** [comment]
check this[https://github.com/YadominJinta/atilo/issues/101](url)
