### ISSUE TITLE
Unable to locate package atilo

### ISSUE THREAD

**Issue by MKamaitachi** [YadominJinta/atilo#101]
Installation里echo命令中的“yadominjinta.github.io/files/”无法访问，“yadominjinta.github.io/”可以访问

**Comment by caochenhins** [comment]
是的呢

**Comment by YadominJinta** [comment]
看了一下，是因为现在 termux 的 pkg 会自动修改 sources.list，~~很傻逼~~，导致atilo的源直接被删了
解决方法是使用 apt 或者将 atilo 的源放在 sources.list.d里
