### ISSUE TITLE
Can not use 'systemctl'

### ISSUE THREAD

**Issue by Pandaver** [YadominJinta/atilo#103]
images: Centos
phone: HUAWEI Mate 20 Pro
Termux Version: 0.101

[root@localhost ~]# systemctl
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by wangxiaoerYah** [comment]
Systemctl needs Linux kernel support 
You can not use systemctl in a proot environment 
@Pandaver

**Comment by YadominJinta** [comment]
Won't Fix.
