### ISSUE TITLE
Extracting stuck

### ISSUE THREAD

**Issue by Idesmi** [YadominJinta/atilo#108]
`atilo pull` gets stuck at Extracting.

This does happen for me when I pull the opensuse image, does not happen with fedora.

**Comment by YadominJinta** [comment]
The new opensuse rootfs contains hard links, but termux's python can't create it (no permission in android).

If you really want to use opensuse, edit `which atilo` and replace the list url to chinese version.

**Comment by YadominJinta** [comment]
If you can find a opensuse rootfs without hard links, pull request is welcome.
