### ISSUE TITLE
拉取镜像太慢卡住不动了

### ISSUE THREAD

**Issue by tiddlerhxy** [YadominJinta/atilo#109]
请看截图：
![Screenshot_20201230_164457_com termux](https://user-images.githubusercontent.com/34333691/103340260-950f9480-4abe-11eb-93ab-29a7ee502285.jpg)

**Comment by YadominJinta** [comment]
应该是你在下载过程中切换过网络环境？

**Comment by YadominJinta** [comment]
`atilo-cn` 用的都是国内源，按说速度不会这么慢的
