### ISSUE TITLE
抱歉打扰您

### ISSUE THREAD

**Issue by hanxinhao000** [YadominJinta/atilo#111]
我在未经过您的允许添加您的脚本到Utermux,
但是我们这个社区有很多人想用到您的linux安装脚本(atilo),
我已在Utermux中添加了您的信息(作者信息)
如果您不满意,请第一时间联系我
我会下架这个版本
给您带来麻烦
实在抱歉

**Comment by YadominJinta** [comment]
可以，保留作者信息即可
