### ISSUE TITLE
Can Linux installed under termux share files under termux

### ISSUE THREAD

**Issue by wangmings** [YadominJinta/atilo#112]
termux version: 0.108 
Android version: 10

Question: Can the Linux installed with atilo share the files or directories under termux in the installed Linux?

**Comment by Tastade** [comment]
Да, Linux, установленный с помощью Atilo в Termux, может предоставлять общий доступ к файлам и каталогам в Termux. Вот несколько способов сделать это:
1. Общая файловая система Android:
 * По умолчанию, Linux, установленный через Atilo, будет иметь доступ к некоторым частям файловой системы Android, обычно расположенным в каталоге `$HOME/storage`.
 * Вы можете создавать файлы и каталоги в этих общих местах как из Termux, так и из установленной Linux-среды.
 * Чтобы получить доступ ко всему хранилищу Android, вам может потребоваться выполнить команду termux-setup-storage в Termux и предоставить необходимые разрешения. Это создаст символические ссылки в `$HOME/storage` на различные разделы вашего хранилища.
2. Связывание каталогов (Bind Mounts):
 * Внутри установленной Linux-среды вы можете использовать команду mount с опцией `--bind` для создания точки монтирования, которая сделает каталог из Termux доступным внутри Linux.
 * Например, чтобы сделать каталог Termux `$HOME/my_shared_folder` доступным в Linux как /mnt/termux_share, вы можете выполнить в Linux:
 
 `sudo mount --bind /data/data/com.termux/files/home/my_shared_folder /mnt/termux_share`

   (Путь /data/data/com.termux/files/home/ является стандартным домашним каталогом Termux).
 * Чтобы эта монтировка сохранялась после перезагрузки Linux, вам может потребоваться настроить /etc/fstab внутри Linux.
3. Использование SSH (Secure Shell):
 * Вы можете установить SSH-сервер как в Termux, так и в установленной Linux-среде.
 * После настройки вы можете использовать такие инструменты, как scp (Secure Copy) или sftp (SSH File Transfer Protocol) для безопасной передачи файлов и каталогов между Termux и Linux.
 * Например, из Termux вы можете скопировать файл `my_file.txt` в домашний каталог Linux (предполагая, что SSH-сервер запущен на localhost на порту 8022):
   `scp -P 8022 my_file.txt localhost:/home/linux_user/`

 * Аналогично, вы можете копировать файлы из Linux в Termux.
4. Использование сетевых протоколов (например, NFS, Samba):
 * Если вам нужен более расширенный общий доступ к файлам, вы можете настроить сетевые файловые системы, такие как NFS (Network File System) или Samba, внутри установленной Linux-среды.
 * Это позволит вам монтировать каталоги Linux в Termux (при наличии соответствующих клиентских приложений в Termux) или наоборот, если вы настроите сервер в Termux.
Выбор наиболее подходящего метода зависит от ваших конкретных потребностей и того, насколько часто вам нужно обмениваться файлами между Termux и установленной Linux-средой. Для простых задач общий доступ через файловую систему Android или связывание каталогов могут быть наиболее удобными. Для более безопасной и гибкой передачи файлов SSH является отличным вариантом. Сетевые файловые системы подходят для более сложных сценариев общего доступа.
