### ISSUE TITLE
Ubuntu使用sudo报错

### ISSUE THREAD

**Issue by newdixue** [YadominJinta/atilo#15]
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: unable to load /usr/lib/sudo/sudoers.so: /usr/lib/sudo/sudoers.so: cannot stat shared object: Bad file descriptor
sudo: fatal error, unable to load plugins

**Comment by myfreess** [comment]
proot还要啥自行车 @newdixue

**Comment by YadominJinta** [comment]
Look at https://github.com/sdrausty/termux-archlinux/issues/4
