### ISSUE TITLE
请问termux更新的时候报错是啥原因呢？是不是跟nghttp2有关

### ISSUE THREAD

**Issue by sbkk000** [YadominJinta/atilo#16]
apt update

CANNOT LINK EXECUTABLE: could not load library "libcurl.so" needed by "/data/data/com.termux/files/usr/lib/apt/methods/https"; caused by could not load library "libnghttp2.so" needed by "libcurl.so"; caused by library "libnghttp2.so" not found
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https returned an error code (1)
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/termux/dists/stable/InRelease 
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by YadominJinta** [comment]
请问这个问题跟我这个项目有什么关系？

这种问题你不去Termux那边查issues而是来我这里？
