### ISSUE TITLE
想跑CentOS是不是就跟atilo无缘了，(+_+)😂😂😂

### ISSUE THREAD

**Issue by sbkk000** [YadominJinta/atilo#17]
CentOS7 armv7版的有么

Linux deploy里面的centos7进VNC一片黑屏，想试试看termux能不能搞得通

**Comment by YadominJinta** [comment]
Docker是有rootfs的,https://github.com/CentOS/sig-cloud-instance-images/tree/CentOS-7armhfp 
之前因为没有国内源的原因放弃了，既然我已经分出了EN版本，是可以考虑一下，这个周末搞定吧。

**Comment by YadominJinta** [comment]
话说我很好奇，在手机上用CentOS有什么意义吗？

**Comment by myfreess** [comment]
大概学运维的很需要？ @YadominJinta

**Comment by YadominJinta** [comment]
Add CentOS in v1.3
