### ISSUE TITLE
太奇怪了

### ISSUE THREAD

**Issue by myfreess** [YadominJinta/atilo#18]
curl "https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/debian/stretch/${time_arch}/default/" -o tmp.html
                                        ttime=`sed -n '7p' tmp.html | cut -d'>' -f2 | cut -d'<' -f1`  
        rm tmp.html
                                        aarch64=https://mirror.tuna.tsinghua.edu.cn/lxc-images/images/debian/stretch/arm64/default/${ttime}rootfs.tar.xz
                                        arm=https://mirror.tuna.tsinghua.edu.cn/lxc-images/images/debian/stretch/armhf/default/${ttime}rootfs.tar.xz
                                        zip=pJx
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--  0     0    0     0    0     0      0      0 --:--100   169  100   169    0     0    380      0 --:--:-- --:--:-- --:--:--   379
[~/workdir]▶ echo $aarch64
https://mirror.tuna.tsinghua.edu.cn/lxc-images/imagrootfs.tar.xzetch/arm64/default/
[~/workdir]▶

我把atlio获取debian url的命令单独拖出来运行，得到的结果如上。
我使用的是zsh,没用ohmyzsh.

**Comment by YadominJinta** [comment]
第一条命令的${time_arch}是空的啊

**Comment by YadominJinta** [comment]
那个，你有时间的话，能帮我看一下https://github.com/YadominJinta/atilo/issues/19 吗？
问题是rootfs在/kali-linux/，你看一下能不能改一下解压参数，直接暴力的用if判断都行，我最近没有时间写

**Comment by myfreess** [comment]
@YadominJinta 看起来完全是Nethunter的rootfs的锅，换个rootfs得了。
 https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Rootfs/Kali/arm64/kali-rootfs-arm64.tar.gz
https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Rootfs/Kali/armhf/kali-rootfs-armhf.tar.gz
刚刚试了，完全ok
