### ISSUE TITLE
安装kali时报错

### ISSUE THREAD

**Issue by L3ss-dev** [YadominJinta/atilo#19]
默认安装会报fatal错误，看了下代码发现需要把./atilo/kali/kail-linux(好像这个？)重新命名并放到./atilo/kail这个位置，删掉原kali文件夹，安装完毕后，出现bash: xmlalloc:.././locale.c:81:cannot allocate 2 bytes (0 bytes allocated)错误，有人知道这个问题怎么解决么？

**Comment by YadominJinta** [comment]
Fixed
