### ISSUE TITLE
安装tigervnc-server时报错

### ISSUE THREAD

**Issue by zhangew** [YadominJinta/atilo#22]
前面安装fedora正常，并且startfedora了。
但安装tigervnc-server时报错了，请教一下能不能解决，谢谢。
(64/66): mesa-libGL-18.0.5-4.f 436 kB/s | 182 kB     00:00
(65/66): mesa-dri-drivers-18.0 431 kB/s |  11 MB     00:25
(66/66): llvm-libs-6.0.1-8.fc2 426 kB/s |  14 MB     00:33
---------------------------------------------------------------
Total                          761 kB/s |  39 MB     00:53
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                       1/1
  Installing       : perl-Exporter-5.72-396.fc28.noarc    1/66
  Installing       : perl-Carp-1.42-396.fc28.noarch       2/66
  Installing       : perl-libs-4:5.26.2-414.fc28.aarch    3/66
Error unpacking rpm package perl-libs-4:5.26.2-414.fc28.aarch64
Error unpacking rpm package perl-libs-4:5.26.2-414.fc28.aarch64
error: unpacking of archive failed on file /usr/lib64/libperl.so.5.26;5beee106: cpio: symlink
  Installing       : libICE-1.0.9-12.fc28.aarch64         4/66
Error unpacking rpm package libICE-1.0.9-12.fc28.aarch64
Error unpacking rpm package libICE-1.0.9-12.fc28.aarch64
error: perl-libs-4:5.26.2-414.fc28.aarch64: install failed
error: unpacking of archive failed on file /usr/lib64/libICE.so.6;5beee106: cpio: symlink
  Installing       : libstdc++-8.2.1-5.fc28.aarch64       5/66
Error unpacking rpm package libstdc++-8.2.1-5.fc28.aarch64
Error unpacking rpm package libstdc++-8.2.1-5.fc28.aarch64
error: libICE-1.0.9-12.fc28.aarch64: install failed
error: unpacking of archive failed on file /usr/lib64/libstdc++.so.6;5beee106: cpio: symlink
  Installing       : libSM-1.2.2-8.fc28.aarch64           6/66
Error unpacking rpm package libSM-1.2.2-8.fc28.aarch64
Error unpacking rpm package libSM-1.2.2-8.fc28.aarch64
error: libstdc++-8.2.1-5.fc28.aarch64: install failed
error: unpacking of archive failed on file /usr/lib64/libSM.so.6;5beee106: cpio: symlink
  Installing       : perl-Scalar-List-Utils-3:1.49-2.f    7/66
Error unpacking rpm package perl-Scalar-List-Utils-3:1.49-2.fc28.aarch64
Error unpacking rpm package perl-Scalar-List-Utils-3:1.49-2.fc28.aarch64
error: libSM-1.2.2-8.fc28.aarch64: install failed
error: unpacking of archive failed: cpio: mkdir failed - Permission denied
  Installing       : libxshmfence-1.3-1.fc28.aarch64      8/66
Error unpacking rpm package libxshmfence-1.3-1.fc28.aarch64
Error unpacking rpm package libxshmfence-1.3-1.fc28.aarch64
error: perl-Scalar-List-Utils-3:1.49-2.fc28.aarch64: install failed
error: unpacking of archive failed on file /usr/lib64/libxshmfence.so.1;5beee106: cpio: symlink
  Installing       : libXau-1.0.8-11.fc28.aarch64         9/66
Error unpacking rpm package libXau-1.0.8-11.fc28.aarch64
Error unpacking rpm package libXau-1.0.8-11.fc28.aarch64

**Comment by YadominJinta** [comment]
似乎是Fedora的问题，29似乎没有这个问题，请尝试使用新版本安装29

**Comment by zhangew** [comment]
谢谢作者回复！

由于我还是不太了解怎么安装29（atilo install fedora安装的是28），因此我试着安装了ubuntu18.04:
atilo install ubuntu
startubuntu

然后参照这里弄好了桌面和vnc（注意，所有文中的sudo都不用sudo，另外安装xfce的时候，会报几个权限不足的问题，据temmux issue里面说是Android8特有，但我没理会）：
https://www.howtoing.com/how-to-install-and-configure-vnc-on-ubuntu-18-04

非常感谢！我本来以为只有Linux Deploy能搞GUI。现在Termux终于完全实用了。

下一步准备搞中文化了。

**Comment by zhangew** [comment]
原来29要dnf update
