### ISSUE TITLE
terminated with signal 11

### ISSUE THREAD

**Issue by Flyfish233** [YadominJinta/atilo#25]
`proot info: vpid 1: terminated with signal 11`
`[ 全部完成 ]`
`startubuntu 以开始`
`$ startubuntu`
`:proot info: vpid 1: terminated with signal 11`

Debian Arch 等发行版错误相同。

Xiaomi Mi 4,Android 8.1

**Comment by myfreess** [comment]
这是proot而非atilo的问题，去proot的issues区吧 @Flyfish233

**Comment by YadominJinta** [comment]
According to https://github.com/termux/termux-packages/issues/258 

The problem is due to Android Kernel.
Try `export PROOT_NO_SECCOMP=1` , if it doesn't work, give it up.

**Comment by 9990242854** [comment]
Your trick isnt work in my redmi 6A
$ export PROOT_NO_SECCOMP=1
$ ls
admin_penal      parrot.sh
parrot-binds     start-parrot.sh
parrot-fs
$ ./start-parrot.sh
bash: [: : integer expression expected
proot info: vpid 1: terminated with signal 7

termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 4.9.77+ #1 SMP PREEMPT Mon Jan 21 22:49:54 WIB 2019 armv7l Android
Termux-packages arch:
arm
Android version:
8.1.0
Device manufacturer:
Xiaomi
Device model:
Redmi 6A
Please fix it

**Comment by rudy507** [comment]
./start-kali.sh
proot info: vpid 1: terminated with signal 11
Bagaimana cara mengatasi problem ini.

**Comment by Georgejnr01** [comment]
Please help me see if I did something wrong
It worked the  first time but now its not working

$ ./start-kali.sh
proot info: vpid 1: terminated with signal 11
$ export PROOT_NO_SECCOMP=1
$ ./start-kali.sh
bash: [: : integer expression expected
$

**Comment by YadominJinta** [comment]
@Georgejnr01 Why you're delievering a AnLinux issues in atilo repo?
Please go to [EXALAB/AnLinux-Resources](https://github.com/EXALAB/AnLinux-Resources).
