### ISSUE TITLE
一直卡在Processing triggers for systemd(239-13)

### ISSUE THREAD

**Issue by cok3307788** [YadominJinta/atilo#27]
魅蓝note6 ,flyme6 ,base on Android 7.1.2
已经完全root(第三方rec刷了superuser)，安装了busybox，f-droid版termux0.65，按照脚本执行无遗漏步骤，确认root已经授权给termux了
在Processing triggers for systemd(239-13)卡了6个小时，安装的是kali

**Comment by myfreess** [comment]
建议：用Linuxdeploy @cok3307788

**Comment by YadominJinta** [comment]
直接退掉termux的进城，重新进去以后
```
startkali
```
就可以用了
