### ISSUE TITLE
I686 

### ISSUE THREAD

**Issue by reinethernal** [YadominJinta/atilo#28]
Asus z00ad
atilo install ubuntults
[ Unknown architecture i686]
$ atilo install centos
[ Unknown architecture i686]
$ atilo install debian
[ Unknown architecture i686]
$ atilo install fedora
[ Unknown architecture i686]
$ atilo install arch
[ Unknown architecture i686]
$ atilo install alpine
[ Unknown architecture i686]
$

**Comment by YadominJinta** [comment]
Don't support i686.

**Comment by reinethernal** [comment]
Can you make support for i686?

**Comment by YadominJinta** [comment]
I won't have time to update it  before I graduate from high school next year.
Maybe you can try https://github.com/Neo-Oli/termux-ubuntu or https://github.com/Hax4us/TermuxAlpine
