### ISSUE TITLE
下载完清华的镜像源卡住

### ISSUE THREAD

**Issue by pigeon2049** [YadominJinta/atilo#3]
本地已经下好的情况下还会重新下载镜像文件
并且下载完成后卡死
没有解压的显示

**Comment by YadominJinta** [comment]
只是我关掉了进度显示
之前有人建议我关掉显示，接下来我会增加进度条

**Comment by seashell11234455** [comment]
略微有些尴尬

**Comment by pigeon2049** [comment]
另外下载的arch有问题
无论安装什么包都提示签名验证失败
后来我放弃用你的脚本装arch了用了隔壁的项目
隔壁的装arch后有额外处理可以直接装包就和正常的一样了
https://github.com/sdrausty/TermuxArch
