### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by 321456987lyk** [YadominJinta/atilo#31]
报错了怎么办啊proot warning: can't sanitize binding "/sdcard": No such file or directory
CANNOT LINK EXECUTABLE "/bin/bash": library "libandroid-support.so" not found
proot info: vpid 1: terminated with signal 6

**Comment by WeihuaGu** [comment]
我的是proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/.atilo/ubuntu, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by WeihuaGu** [comment]
在安装 ubuntu 时出的错

**Comment by WeihuaGu** [comment]
@321456987lyk termux-setup-storage 这个问题好像已经有人问过了，@#9
