### ISSUE TITLE
startubuntu后出现下面这些

### ISSUE THREAD

**Issue by fire-keeper** [YadominJinta/atilo#33]
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997                         groups: cannot find name for group ID 20132
groups: cannot find name for group ID 50132

现在没有影响使用，不知道有没有什么未知问题

**Comment by Flyfish233** [comment]
遇类似问题

[ 升级中 ... ]
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
Reading package lists... Done
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: Method gave invalid 400 URI Failure message: Failed to set new group ids - setresgid (38: Function not implemented)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
[ 全部完成 ]
startubuntu 以开始
 ~  startubuntu
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 20155
groups: cannot find name for group ID 50155

**Comment by YadominJinta** [comment]
@Flyfish233 你的问题是termux的问题，用`unset LD_PRELOAD`

**Comment by YadominJinta** [comment]
``` bash
startubuntu
echo "touch ~/.hushlogin" >> ~/.bashrc
```

**Comment by spcharc** [comment]
setegid 65534 failed - setegid (38: Function not implemented)
setegid 0 failed - setegid (38: Function not implemented)
这俩是安卓9才有的问题。建议降级安卓8
