### ISSUE TITLE
请问怎么备份安装好的ubuntu18.04？

### ISSUE THREAD

**Issue by zhangew** [YadominJinta/atilo#34]
用了一个月，感觉很好。真是感谢作者！

想请教一下，如果以后换手机，如果还想把装好的ubuntu环境移到新手机的termux，要如何备份转移操作？

**Comment by YadominJinta** [comment]
tar打包一下吧

**Comment by myfreess** [comment]
把~/.atilo/ubuntu打个包 @zhangew

**Comment by zhangew** [comment]
多谢！
