### ISSUE TITLE
硬是没看明白图形界面那里的vim添加的代码

### ISSUE THREAD

**Issue by voidlhf** [YadominJinta/atilo#37]
# For Fedora
$ startfedora
dnf makecache
dnf install tigervnc-server 
dnf groupinstall LXDE
# for Debian
$ startdebian
apt update
apt install --no-install-recommands tigervnc-standalone-server lxde

# 启动Vnc
vncserver :1
# 与上面相同
# Fedora
vim ~/.vnc/xstartup
--- exec /etc/X11/xinit/xinitrc
+++ exec startlxde
killall Xvnc
rm -rf /tmp/X1*
vncserver :1

# Debian 
vim /etc/X11/Xvnc-session
--- exec /etc/X11/Xsession "$@"
+++ exex startlxde
killall Xtigervnc # 这里进程名为Xtigervnc，与Fedora不同
rm -rf /tmp/.X1*

前几行的意思应该是安装tigervnc-server和lxde，但是后面的啥意思啊，看得我一脸懵逼:sweat_smile::sweat_smile:

**Comment by YadominJinta** [comment]
就是diff里面的删除和增加啊
