### ISSUE TITLE
Please consider add $LANG environment variable, and add /usr/local/ in $PATH

### ISSUE THREAD

**Issue by spcharc** [YadominJinta/atilo#38]
++ command+=" $LANG=C.UTF-8"
this could help display Asian characters correctly

-- command+=" PATH=/bin:/usr/bin:/sbin:/usr/sbin"
++ command+=" PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
user installed packages (not from the package manager, but compiled and installed by user himself) are usually in /usr/local/(bin or sbin)
Linux distributions usually have /usr/games and /usr/local/games in $PATH, but they are barely used...

**Comment by myfreess** [comment]
ok,changed @spcharc

**Comment by spcharc** [comment]
I'm upgrading atilo today and found out LANG is still not there @myfreess 

I made a mistake in the original post though... it should be
command+=" LANG=C.UTF-8"

**Comment by spcharc** [comment]
LANG helps displaying Asian characters, please consider adding it

**Comment by YadominJinta** [comment]
I added it.
Will this satisfies you?
![this](https://i.loli.net/2019/01/30/5c5172f85858c.png)
