### ISSUE TITLE
using gui on alpine

### ISSUE THREAD

**Issue by darkoverlordofdata** [YadominJinta/atilo#43]
After using atilo to install alpine, I found this article:
[https://www.hax4us.com/2018/12/setup-basic-gui-in-termuxalpine.html](https://www.hax4us.com/2018/12/setup-basic-gui-in-termuxalpine.htmll)

But it gets an error, after the last step "DISPLAY=:1 xfce4-terminal &", I get "D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open /etc/machine-id: no such file or directory", and when I launch the vnc client, all I get is black screen and a mouse cursor. I notice in the article, you refer to your other script for installing alpine - [https://github.com/Hax4us/TermuxAlpine](https://github.com/Hax4us/TermuxAlpine). So, I'm confused, which of your two install scripts should I use?

**Comment by YadominJinta** [comment]
I can't tell which one is better.
Actually, the two scripts use the same rootfs,so there should be no difference.
Try `export DISPLAY=:0 ; startxfce` . I used to ran lxde in alpine successfully.

**Comment by darkoverlordofdata** [comment]
Doh! I was using startx. Rookie mistake, I haven't played much at this layer till now.
Thanks
