### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Shadcloud** [YadominJinta/atilo#44]
/data/data/com.termux/files/usr/bin/atilo: line 282: /data/data/com.termux/files/home/.atilo/ubuntu/etc/resolv.conf: No such file or directory
/data/data/com.termux/files/usr/bin/atilo: line 283: /data/data/com.termux/files/home/.atilo/ubuntu/etc/profile: No such file or directory
/data/data/com.termux/files/usr/bin/atilo: line 287: etc/apt/sources.list: No such file or directory
[ 升级中 ... ]
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/.atilo/ubuntu, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by YadominJinta** [comment]
``` bash
atilo remove ubuntu
atilo clean
bash -x $PREFIX/bin/atilo install ubuntu
```
如果问题仍然存在，请将更详细的报错信息贴出来

**Comment by Shadcloud** [comment]
+ tips '[ 配置中 ...]'
+ echo -e '\033[32m[ 配置中 ...]\033[0m'
[ 配置中 ...]
+ rm -r /data/data/com.termux/files/home/.atilo/ubuntu/etc/resolv.conf
+ echo 'nameserver 8.8.8.8'
+ echo 'export USER=root'
+ '[' '!' -z 'deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports cosmic main restricted universe multiverse\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports cosmic-updates main restricted universe multiverse' ']'
+ cd /data/data/com.termux/files/home/.atilo/ubuntu
+ echo -e 'deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports cosmic main restricted universe multiverse\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports cosmic-updates main restricted universe multiverse'
+ cat
+ chmod +x /data/data/com.termux/files/usr/bin/startubuntu
+ tips '[ 升级中 ... ]'
+ echo -e '\033[32m[ 升级中 ... ]\033[0m'
[ 升级中 ... ]
+ startubuntu apt update
proot info: vpid 1: terminated with signal 11
+ tips '[ 全部完成 ]'
+ echo -e '\033[32m[ 全部完成 ]\033[0m'
[ 全部完成 ]
+ tips 'startubuntu 以开始'
+ echo -e '\033[32mstartubuntu 以开始\033[0m'
startubuntu 以开始
$ startubuntu
proot info: vpid 1: terminated with signal 11
$

**Comment by YadominJinta** [comment]
`proot info: vpid 1: terminated with signal 11` 我之前以为是内核问题，现在看来应该是Ubuntu 的问题，换个发行版试试吧

**Comment by YadominJinta** [comment]
试试`termux-chroot`能不能用，不能用的话那就是内核问题

**Comment by cyxconfluence** [comment]
proot warning:can't chdir("/root/.")in the guest rootfs:no such file or directory

**Comment by myfreess** [comment]
@cyxconfluence 

请确保网络畅通

```shell
atilo clean
atilo remove <你装的发行版名称>
```

然后重新安装 。

还不行，建议自己写脚本启动：/
