### ISSUE TITLE
pie upgrade

### ISSUE THREAD

**Issue by diehard88** [YadominJinta/atilo#45]
yesterday my note 8 upgraded to Pie.

did it break atilo?

  
![atilo](https://user-images.githubusercontent.com/25366502/55574484-807c4d80-56da-11e9-8938-4f51323c7e0a.jpg)

**Comment by diehard88** [comment]
/data/user/0/com.samsung.android.securitylogagent/files/

**Comment by diehard88** [comment]
![pie](https://i.imgur.com/giAXvkk.jpg)



#47

**Comment by etnperlong** [comment]
Same issue in pie rom. Waiting for an update

**Comment by diehard88** [comment]
upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
$ startkali
root@localhost:~# apt update
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
Reading package lists... Done
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: Method gave invalid 400 URI Failure message: Failed to set new group ids - setresgid (38: Function not implemented)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
root@localhost:~#

**Comment by YadominJinta** [comment]
Please report this problem to termux-packages.

**Comment by diehard88** [comment]
this is happening inside kali.

the same happens with the other images such as ubuntu.
