### ISSUE TITLE
i

### ISSUE THREAD

**Issue by zaoqi-unsafe** [YadominJinta/atilo#46]
ubuntults
$ atilo install arch
[ Checking for requirements ... ]
[ Downloading ... ]
curl: (48) An unknown option was passed in to libcurl
[ Extracting ... ]
pv: arch: No such file or directory
[ Configuring ...]
/data/data/com.termux/files/usr/bin/atilo: line 268: /data/data/com.termux/files/home/.atilo/arch/etc/resolv.conf: No such file or directory
/data/data/com.termux/files/usr/bin/atilo: line 269: /data/data/com.termux/files/home/.atilo/arch/etc/profile: No such file or directory
[ Upgrading ... ]
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/.atilo/arch, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
[ All done ]
startarch To start

**Comment by diehard88** [comment]
3.1415926535?

**Comment by YadominJinta** [comment]
pkg in libcurl

**Comment by myfreess** [comment]
看起来Termux初始化rootfs的libcurl有问题 @YadominJinta 我也遇到此情况了
