### ISSUE TITLE
Cant install ANY linux systems

### ISSUE THREAD

**Issue by ghost** [YadominJinta/atilo#47]
I tried installing all of them but got the same error, here I tried kali

$ atilo install kali
[ Checking for requirements ... ]
[ Downloading ... ]
curl: (48) An unknown option was passed in to libcurl
[ Extracting ... ]
pv: kali: No such file or directory
[ Configuring ...]
/data/data/com.termux/files/usr/bin/atilo: line 268: /data/data/com.termux/files/home/.atilo/kali/etc/resolv.conf: No such file or directory
/data/data/com.termux/files/usr/bin/atilo: line 269: /data/data/com.termux/files/home/.atilo/kali/etc/profile: No such file or directory
[ Upgrading ... ]
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/.atilo/kali, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
[ All done ]
startkali To start

$ startkali
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/.atilo/kali, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by myfreess** [comment]
@Hyperscope35  please run:
```
pkg i libcurl -y
```

and restart install

**Comment by ghost** [comment]
@myfreess the install worked but now im getting another error and cant install any packages

E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: Method gave invalid 400 URI Failure message: Failed to set new group ids - setresgid (38: Function not implemented)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)

**Comment by diehard88** [comment]
@Hyperscope35 

same here.

started after update to pie.

no problems with other devices still on oreo.
