### ISSUE TITLE
找不到tmp.html

### ISSUE THREAD

**Issue by liuwenlang** [YadominJinta/atilo#49]
atilo install ubuntu
[ 检查依赖中 ]
sed: tmp.html: No such file or directory
rm: can't remove 'tmp.html': No such file or directory
sed: tmp.html: No such file or directory
rm: can't remove 'tmp.html': No such file or directory
[ 正在下载中 ... ]
CANNOT LINK EXECUTABLE "curl": library "libz.so.1" not found
[ 解压中 ... ]
pv: ubuntu: No such file or directory
[ 配置中 ...]
/data/data/com.termux/files/usr/bin/atilo: line 282: /data/data/com.termux/files/home/.atilo/ubuntu/etc/resolv.conf: No such file or directory
/data/data/com.termux/files/usr/bin/atilo: line 283: /data/data/com.termux/files/home/.atilo/ubuntu/etc/profile: No such file or directory
/data/data/com.termux/files/usr/bin/atilo: line 287: etc/apt/sources.list: No such file or directory
[ 升级中 ... ]
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/.atilo/ubuntu, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
[ 全部完成 ]
startubuntu 以开始

**Comment by YadominJinta** [comment]
Already fixed in new commit. Thanks for your issue.
