### ISSUE TITLE
安装Arch，卡住了！！

### ISSUE THREAD

**Issue by saltpi** [YadominJinta/atilo#5]
- 如图所示
![screenshot_2018-08-21-18-18-18-424_com termux](https://user-images.githubusercontent.com/33711476/44396214-cb43bd80-a56e-11e8-9738-47ee50c6f3ec.png)

**Comment by Throidal** [comment]
update就写了Fedora的脚本 其他没写。。我这装Arch也是到update就不动了

**Comment by YadominJinta** [comment]
直接退出Termux，重开，输入startarch就能用了

**Comment by YadominJinta** [comment]
**Already Fixed**
