### ISSUE TITLE
前面几个发行版，安装键盘用不了。

### ISSUE THREAD

**Issue by leijux** [YadominJinta/atilo#50]
比如，Backpace键，效果是光标向右移动

**Comment by liuxsdev** [comment]
同样的问题，我装的是arch，退格键和方向键都不灵。安装时卡在Updating trust database...，但强制结束后，startarch也是可以正常工作的。重新装了两次都是这样。

**Comment by leijux** [comment]
我前面的都安装了一遍

**Comment by YadominJinta** [comment]
或许跟$TERM变量有关，尝试在$(which startarch)中修改$TERM=xterm-256
