### ISSUE TITLE
执行

### ISSUE THREAD

**Issue by dnslin** [YadominJinta/atilo#53]
pkg in atilo-cn
的时候
返回Malformed line 1 in source list /data/data/com.termux/files/usr/etc/apt/sources.list (type)
E: The list of sources could not be read.

**Comment by YadominJinta** [comment]
检查一下sources.list有没有出错，报错说的第一行异常，而atilo的源不应该出现在第一行。

**Comment by blankmakering** [comment]
谢谢了  我本地查看了文件，，发现第一行出现了乱码删掉后  就行了
