### ISSUE TITLE
cannot change password

### ISSUE THREAD

**Issue by WqyJh** [YadominJinta/atilo#54]
![Screenshot_20190706-232724](https://user-images.githubusercontent.com/15232241/60758162-7b66cb80-a046-11e9-9dbb-a7dcdae69ade.png)

Failed to change password as is shown above.

**Comment by YadominJinta** [comment]
I'm sorry that I can't reproduce this error.
[![Screenshot_2019-07-26-12-27-45-058_com.termux.jpg](https://i.loli.net/2019/07/26/5d3a8189872a935329.jpg)](https://i.loli.net/2019/07/26/5d3a8189872a935329.jpg)
