### ISSUE TITLE
用atilo装的archlinux无法使用makepkg

### ISSUE THREAD

**Issue by chinuno-usami** [YadominJinta/atilo#55]
Android系统版本6.0.1
未root
termux为最新版本，内部包也是更新到最新了
本来就为了aur用的archlinux，结果makepkg都用不了
makpkg运行时不停报
```
/usr/share/makepkg/util/pkgbuild.sh:行69: /dev/fd/62: 没有那个文件或目录
```
和
```
/usr/share/makepkg/source/file.sh:行44: /dev/fd/62: 没有那个文件或目录
```
大概搜了一下隔壁`TermuxArch`好像也有这样的问题

**Comment by myfreess** [comment]
请问fakeroot是否换成fakeroot-tcp了?

**Comment by chinuno-usami** [comment]
把fakeroot替换成fakeroot-tcp后还是一样的问题。
报错的地方还没进fakeroot应该不是fakeroot的问题。
arch环境的/dev应该是proot的时候从termux映射进去的，但是termux环境下访问/dev是访问不了的
是需要root环境吗？

**Comment by myfreess** [comment]
网上找的，这个目录下存放的是当前进程的文件句柄。

我这里/dev目录下没有fd，但是可以用/proc/<进程ID>/fd代替

**Comment by chinuno-usami** [comment]
我在`startarch`脚本里加了 
```bash
command+=" -b /proc/self/fd:/dev/fd"
```
把`/proc/self/fd`挂载到proot环境下的`/dev/fd`
可以通过/dev/fd看到当前进程的文件，但是问题依然存在
我的猜测是
`makepkg`脚本会通过子进程的方式开新的shell执行脚本，两个进程间通过`/dev/62`(匿名管道)通信。
我在派生出来的子进程`/proc/<子进程id>/fd`中能看到`62`，但是`/proc/<父进程id>/fd`中没有。
父进程无法读取到`/dev/fd/62`文件无法和子进程交互。是不是跟fakeroot一样由于环境不支持匿名管道这类ipc导致的

**Comment by myfreess** [comment]
由于读书过少，无能为力:sweat:
