### ISSUE TITLE
can't start kali with termux on Huawei P30

### ISSUE THREAD

**Issue by caohm** [YadominJinta/atilo#61]
$ startkali
proot warning: can't sanitize binding "/sdcard": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /home/.atilo/kali, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp', please report this error.
$

**Comment by rvt-hub** [comment]
Same shit
