### ISSUE TITLE
大佬，Arch挂了

### ISSUE THREAD

**Issue by Aleksanaa** [YadominJinta/atilo#62]
安装完后提示
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
mkdir: cannot create directory '/etc': Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
touch: cannot touch '/etc/pacman.d/gnupg//pubring.gpg': Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
touch: cannot touch '/etc/pacman.d/gnupg//secring.gpg': Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
FATAL: error reading `/proc/sys/crypto/fips_enabled' in libgcrypt: Function not implemented
/bin/pacman-key: line 223: 20113 Aborted                 "${GPG_PACMAN[@]}" --update-trustdb
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
chmod: cannot access '/etc/pacman.d/gnupg//pubring.gpg': Function not implemented
chmod: cannot access '/etc/pacman.d/gnupg//trustdb.gpg': Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
chmod: cannot access '/etc/（这一行没复制完
nction not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
chmod: cannot access '/etc/pacman.d/gnupg//gpg.conf': Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
/bin/pacman-key: line 205: /etc/pacman.d/gnupg//gpg.conf: Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
/bin/pacman-key: line 205: /etc/pacman.d/gnupg//gpg.conf: Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
/bin/pacman-key: line 205: /etc/pacman.d/gnupg//gpg.conf: Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
/bin/pacman-key: line 205: /etc/pacman.d/gnupg//gpg.conf: Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
touch: cannot touch '/etc/pacman.d/gnupg//gpg-agent.conf': Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
chmod: cannot access '/etc/pacman.d/gnupg//gpg-agent.conf': Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
/bin/pacman-key: line 205: /etc/pacman.d/gnupg//gpg-agent.conf: Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
ob-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
FATAL: error reading `/proc/sys/crypto/fips_enabled' in libgcrypt: Function not implemented
/bin/pacman-key: line 177: 20128 Aborted                 "${GPG_PACMAN[@]}" --gen-key --batch <<EOF
%echo Generating pacman keyring master key...
Key-Type: RSA
Key-Length: 2048
Key-Usage: sign
Name-Real: Pacman Keyring Master Key
Name-Email: pacman@localhost
Expire-Date: 0
%no-protection
%commit
%echo Done
EOF

==> Updating trust database...
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
FATAL: error reading `/proc/sys/crypto/fips_enabled' in libgcrypt: Function not implemented
/bin/pacman-key: line 535: 20130 Aborted                 "${GPG_PACMAN[@]}" --batch --check-trustdb
因为不方便粘贴，中间可能漏掉了少部分内容
预装的软件都可以使用，比如nano，但是无法安装新软件，会在下载后提示删除软件包。网上几乎所有方法都试过，比如把siglevel改成never之类的，或者重装keyring、gnupg，都没用。
手机是Huawei P10Plus，在emui9.0，emui9.1，openkirin omni上均有此问题。（装过你提供的proot，没用）
termux换了几个版本，在保证网络通畅的情况下多次下载，都出现了这个问题。
记得在4月份的时候还可以正常使用的😥

**Comment by Aleksanaa** [comment]
安装archlinux-keyring显示
resolving dependencies...
looking for conflicting packages...

Packages (1) archlinux-keyring-20190123-2

Total Download Size:   0.67 MiB
Total Installed Size:  0.95 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
error: failed retrieving file 'archlinux-keyring-20190123-2-any.pkg.tar.xz' from mirrors.tuna.tsinghua.edu.cn : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

**Comment by YadominJinta** [comment]
无法重现错误，我觉得是Huawei的锅
