### ISSUE TITLE
Debian installation does not work.

### ISSUE THREAD

**Issue by DarthZedd** [YadominJinta/atilo#63]
$ ./atilo install debian
[ Checking for requirements ... ]
[ Downloading ... ]
###################################################################################################### 100.0%
[ Extracting ... ]
 176 B 0:00:00 [2.89MiB/s] [==============================================================>] 100%
[ Configuring ...]
./atilo: line 280: /data/data/com.termux/files/home/.atilo/debian/etc/resolv.conf: No such file or directory
./atilo: line 281: /data/data/com.termux/files/home/.atilo/debian/etc/profile: No such file or directory
[ Upgrading ... ]
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/.atilo/debian, cwd = /, $PATH=(null))
fatal error: see `proot --help`.
[ All done ]
startdebian To start
$ startdebian
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/.atilo/debian, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by YadominJinta** [comment]
#64
