### ISSUE TITLE
Ubuntu installation errors.

### ISSUE THREAD

**Issue by DarthZedd** [YadominJinta/atilo#64]
$ ./atilo install ubuntu
[ Checking for requirements ... ]
[ Downloading ... ]
[ Skip download ]
[ Extracting ... ]
24.2MiB 0:00:05 [4.32MiB/s] [============================================================>] 100%
[ Configuring ...]
[ Upgrading ... ]
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Function not implemented
Reading package lists... Done
E: Method gave invalid 400 URI Failure message: Failed to set new user ids - setresuid (1: Operation not permitted)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
[ All done ]
startubuntu To start

**Comment by 9514** [comment]
解决没有啊。

**Comment by YadominJinta** [comment]
It's related to Android kernel, and I can't fix it.
Try other distributions.
