### ISSUE TITLE
Ubuntu LTS installing error on Huawei LDN-AL20

### ISSUE THREAD

**Issue by SunsetMkt** [YadominJinta/atilo#65]
atilo install ubuntults
[ 检查依赖中 ]
[ 正在下载中 ... ]
########################################### 100.0%
[ 解压中 ... ]
77.8MiB 0:00:29 [2.64MiB/s] [==>] 100%
[ 配置中 ...]
[ 升级中 ... ]
Reading package lists... Done
E: Method gave invalid 400 URI Failure message: Failed to set new user ids - setresuid (1: Operation not permitted)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
[ 全部完成 ]
startubuntults 以开始
 Huawei  ~  startubuntults             ✔  312
groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 20177
groups: cannot find name for group ID 50177
/bin/lesspipe: 1: cd: can't cd to /bin

**Comment by SunsetMkt** [comment]
And every time when I use some commands:

root@localhost:~# cd /
bash: cd: /: Function not implemented

Maybe it is a problem from proot?

**Comment by 9514** [comment]
china user?ii

**Comment by YadominJinta** [comment]
Problem related to SELinux and Android Kernel can't be fixed.
