### ISSUE TITLE
Centos 安装 Docker 后，无法启动 Docker

### ISSUE THREAD

**Issue by Jsharkc** [YadominJinta/atilo#69]
报错如下：
![image](https://user-images.githubusercontent.com/17465198/68989843-fce92880-0886-11ea-9c01-444c8b161f66.png)

**Comment by YadominJinta** [comment]
Docker need cgroup, namespace and some other kernel features that are usually disabled in android devices.

**Comment by YadominJinta** [comment]
So it won't be usable unless you recompile the kernel.
