### ISSUE TITLE
apt-get update报错

### ISSUE THREAD

**Issue by BA7LCY** [YadominJinta/atilo#7]
E: setgroups 65534 failed - setgroups (38: Function not implemented)
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: setgroups 0 failed - setgroups (38: Function not implemented)
Reading package lists... Done
E: setgroups 65534 failed - setgroups (38: Function not implemented)
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: setgroups 0 failed - setgroups (38: Function not implemented)
E: Method gave invalid 400 URI Failure message: Failed to setgroups - setgroups (38: Function not implemented)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
root@localhost:~#

百度找不到答案

**Comment by YadominJinta** [comment]
Find in google:
https://github.com/Neo-Oli/termux-ubuntu/issues/44

**Comment by BA7LCY** [comment]
usermod -a -G root root

这样吗？

**Comment by YadominJinta** [comment]
@Nokia-1208 这样以后能正常使用吗？

**Comment by BA7LCY** [comment]
还是不行

**Comment by YadominJinta** [comment]
那你不如换一个发行版吧

**Comment by BA7LCY** [comment]
Debian和kali都不行
