### ISSUE TITLE
不能运行ps -ef

### ISSUE THREAD

**Issue by labulakalia** [YadominJinta/atilo#73]
```
[root@localhost ~]# ps -ef
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
```

`[root@localhost ~]# uname -a
Linux localhost 4.9.65-perf-g30ff678 #1 SMP PREEMPT Fri Oct 26 13:10:48 CST 2018 aarch64 aarch64 aarch64 GNU/Linux`
安装的是centos

**Comment by YadominJinta** [comment]
我无法复现这个错误，/proc应该是由proot挂载的，可能是你的Rom内核限制了对/proc的读取

**Comment by labulakalia** [comment]
手机是小米8出现了这个问题，但是在另外的手机重新试了下是正常的

**Comment by zphiliam** [comment]
哎，，， 我遇到同样到问题了，感觉是centos8到问题， 
在termux里执行 `atilo run centos` 进去执行 `ps -ef` 和你同样到问题，
我在termux执行 `atilo run alpine`  进到alpine里执行 `ps -ef ` 没问题
