### ISSUE TITLE
Problem with install kali and other distributions

### ISSUE THREAD

**Issue by dd191** [YadominJinta/atilo#75]
Such a problem. As I understand it, this problem is very common in everyone. I wanted to fix it but could not find information on this problem.

> $ atilo install kali
[ Checking for requirements ... ]
[ Downloading ... ]
[ Skip download ]
[ Extracting ... ]                                      
15.0 B 0:00:00 [18.2KiB/s] [=========>] 100%            
[ Configuring ...]
/data/data/com.termux/files/usr/bin/atilo: line 279: /home/.atilo/kali/etc/resolv.conf: No such file or directory
/data/data/com.termux/files/usr/bin/atilo: line 280: /home/.atilo/kali/etc/profile: No such file or directory
[ Upgrading ... ]                                       
proot warning: can't sanitize binding "/sdcard": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /home/.atilo/kali, cwd = /, $PATH=(null))                         fatal error: see proot --help.
proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp', please report this error.
[ All done ]
startkali To start

> $ startkali
proot warning: can't sanitize binding "/sdcard": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /home/.atilo/kali, cwd = /, $PATH=(null))
fatal error: see proot --help.
proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp', please report this error.

**Comment by YadominJinta** [comment]
`atilo clean && atilo rm kail && atilo install kali`
It happens when last download session not successful.

**Comment by YadominJinta** [comment]
So sorry I am that I didn't notice the download link is expired.
I will update it soon.
