### ISSUE TITLE
update gpg database卡死

### ISSUE THREAD

**Issue by pigeon2049** [YadominJinta/atilo#8]
导入gpg key后
update gpg database卡死

**Comment by YadominJinta** [comment]
？？？

**Comment by YadominJinta** [comment]
能详细一些吗？

**Comment by pigeon2049** [comment]
脚本安装arch过程中，解压完成后添加gpgkey,然后在update trust datebase过程中卡死
我的辣鸡米板4就这样等了两小时==后来放弃装arch了 因为隔壁装termuxarch的脚本也有问题
那个脚本提示安装成功，但是进去后不管怎么换源pacman -S都提示failed to synchronize all databases
ls
atilo
$ ./atilo install arch
[ 检查依赖中/Checking for requirements ... ]
[ 正在下载中/Downloading ... ]
############################################################################## 100.0%
[ 解压中/Extracting ... ]
 419MiB 0:00:19 [21.3MiB/s] [=====================================>] 100%
[ 配置中/Configuring ...]
[ 升级中/Upgrading ... ]
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key 0AC72381A9DAC67D marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/19001B7A1AC5DDF69BEDCD6C0AC72381A9DAC67D.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from archlinuxarm.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 02922214DE8981D14DC2ACABBC704E86B823CD25...
  -> Locally signing key 69DD6C8FD314223E14362848BF7EEF7A9C6B5765...
  -> Locally signing key 9D22B7BB678DC056B1F7723CB55C5315DCD9EE1A...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   3  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   3  signed:   1  trust: 0-, 0q, 0n, 3m, 0f, 0u
gpg: depth: 2  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u
然后到这里会卡住
