### ISSUE TITLE
Please try to obtain other Fedora chroot since dnf instal can not install many many packages

### ISSUE THREAD

**Issue by JanuszChmiel** [YadominJinta/atilo#80]
I have tried to install Orca, Gnome-desktop and I Am getting errrors related to database mismatch.
I have typed
dnf makecache
The metacache have been created successfully.
but dnf install @gnome-desktop
can not install this package.
I do not know, why it is not work. several months ago, it have been possible to install what ever Fedora package user has wanted. Any tips will be very welcomed, because Fedora is perfect distribution.
But something was happen with packaging system.

**Comment by YadominJinta** [comment]
I have tried `dnf install @gnome-desktop`. No error occurs

**Comment by JanuszChmiel** [comment]
Oh I Am very sorry.
So it means, that there is A new hydden issue between Proot, Android 8.0
kernel. I Am very sorry, that I have intruded you.
Because you have deep programmers experiences.
Please try to run installed Orca screen reader by typing dbus-launch orca &
Fedora has some issues with Dbus. Services do not work in chroot so if zou
would have some time and if zou would trz to install Orca or zou can trz to
run mate desktop environment bz dbus-launch mate-session &
As non root user.
My goal is to try if it would be possible to run Mate or if dbus-launch will
not be enough to force Dbus to work.
I have positive experience with this command while working with Arch Linux.
Debian can even start Dbus automatically but every chroot based Linux
distribution have some bigger or smaller problems with Dbus.
I have tried even Opensuse, but it seems to Me, that ARM64 Bit packages of
Gnome, Orca etc is not available on their repositories or I can not find how
to install those packages.
