### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by liunianyuwen** [YadominJinta/atilo#9]
proot warning: can't sanitize binding "/sdcard": No such file or directory

**Comment by YadominJinta** [comment]
termux-setup-storage

**Comment by YadominJinta** [comment]
原因是termux没有开启读写sd卡的权限

**Comment by liunianyuwen** [comment]
data/data/com.termux/files/usr/bin/am: 4: exec: /system/bin/app_process: Operation not permitted

**Comment by liunianyuwen** [comment]
哎

**Comment by YadominJinta** [comment]
???

**Comment by YadominJinta** [comment]
看一下手机设置里面有没有应用权限的相关设置，给Termux分配外置的权限设置成允许
