### ISSUE TITLE
Can't connect into container through SSH

### ISSUE THREAD

**Issue by Jason1737** [YadominJinta/atilo#90]
Hello,I used atilo to run a Debian Container,and I installed openssh-server from apt then changed the sshd port to 2222 and enabled PermitRootLogin.But I can't connect to the container via ssh on ifself or other device and I got this:

Connection to localhost closed.

how to fix this problem? Thanks

**Comment by YadominJinta** [comment]
Use /usr/sbin/sshd -d to see the error log

**Comment by cityofsmiles** [comment]
I have the same problem when I run Fedora 31. I can't ssh from Termux to Fedora. When I run `netstat -tulpn` in Termux, here's the output: 
`
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8022            0.0.0.0:*               LISTEN      11453/sshd
tcp6       0      0 :::8022                 :::*                    LISTEN      11453/sshd
`

In Fedora, here's the output: 
`Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8022            0.0.0.0:*               LISTEN      11453/sshd
tcp6       0      0 :::8022                 :::*                    LISTEN      11453/sshd`

When I run `sshd -d` in Termux, here's the output: 
`debug1: sshd version OpenSSH_8.2, OpenSSL 1.1.1f  31 Mar 2020
debug1: private host key #0: ssh-rsa SHA256:MaHxc2M/zyP7hoZ05W5vIK03NJkAXxfv9m3F4jCR5T4
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:pVdsAJN7XP6jWDWbpItnCncGWXZ8E0N30hfXX/5rSFU
debug1: private host key #2: ssh-ed25519 SHA256:/fsLnSIayyd3qACCWAI0mpqlTQLo7z9/yATCwEWA0bg
debug1: rexec_argv[0]='/data/data/com.termux/files/usr/bin/sshd'
debug1: rexec_argv[1]='-d'
debug1: Bind to port 8022 on ::.
Bind to port 8022 on :: failed: Address already in use.
debug1: Bind to port 8022 on 0.0.0.0.
Bind to port 8022 on 0.0.0.0 failed: Address already in use.
Cannot bind any address.`

While in Fedora: 
`/usr/sbin/sshd -d
debug1: sshd version OpenSSH_8.1, OpenSSL 1.1.1d FIPS  10 Sep 2019
debug1: private host key #0: ssh-rsa SHA256:hAdPg8HAZy7HvvqJHQBXVZPAzYBD/dPPH1H7acPxJmI
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:/3KWuTg5PngEhZUbM2Z+yJ0WKBPOwfbMv8B3sgGRL4c
debug1: private host key #2: ssh-ed25519 SHA256:U87rXpQ1MKZj80deXbOrBIsVJcg/dnVefxHiTxlV14c
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-d'
debug1: Bind to port 8022 on 0.0.0.0.
Bind to port 8022 on 0.0.0.0 failed: Address already in use.
debug1: Bind to port 8022 on 192.168.1.255.
Bind to port 8022 on 192.168.1.255 failed: Address already in use.
debug1: Bind to port 8022 on 127.0.0.1.
Bind to port 8022 on 127.0.0.1 failed: Address already in use.
debug1: Bind to port 8022 on ::.
Bind to port 8022 on :: failed: Address already in use.
debug1: Bind to port 8022 on 192.168.1.2.
Bind to port 8022 on 192.168.1.2 failed: Address already in use.
Cannot bind any address.
`

I tried editing the /etc/ssh/sshd_config in Fedora by changing ports and ListenAddress but the problem persists. I don't know what's wrong. Any ideas?

**Comment by YadominJinta** [comment]
Can't reproduct this issues, sshd works fine on my device.

**Comment by cityofsmiles** [comment]
Do you mind sharing how you configured sshd in Termux and Fedora?

**Comment by YadominJinta** [comment]
I didn't change any thing except the port

**Comment by cityofsmiles** [comment]
Port 8022 in Termux and 22 in Fedora, right?

**Comment by YadominJinta** [comment]
It's obvios that you can't use port 22 in fedora, it need real root priviledge, not proot's fake root, I use 2222 in fedora.

**Comment by cityofsmiles** [comment]
I didn't know that. I'll try it. Thanks!

**Comment by cityofsmiles** [comment]
I just tried using port 2222 in Fedora but the connection refused. Here's the output of ` /usr/sbin/sshd -d`: 
`debug1: sshd version OpenSSH_8.1, OpenSSL 1.1.1d FIPS  10 Sep 2019
debug1: private host key #0: ssh-rsa SHA256:QYl/tqqjz7PdsG1O9r1LBTLRtsd03DzCb/kK2QxRMZ4
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:Avamubdnxp+8ErPuQLk87YZf50W6CG3aD7YJCbYLdqk
debug1: private host key #2: ssh-ed25519 SHA256:lZ4NnrCRew8pq49pEMCX5NvbaAPliRydSzHsyEm/m80
debug1: rexec_argv[0]='/usr/sbin/sshd'
debug1: rexec_argv[1]='-d'
debug1: Bind to port 2222 on 0.0.0.0.
Server listening on 0.0.0.0 port 2222.
debug1: Bind to port 2222 on ::.
Server listening on :: port 2222.
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8
debug1: inetd sockets after dupping: 3, 3
Connection from 192.168.1.4 port 51493 on 192.168.1.4 port 2222 rdomain ""
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2
debug1: match: OpenSSH_8.2 pat OpenSSH* compat 0x04000000
debug1: sshd_selinux_change_privsep_preauth_context: Failed to open SELinux context file [preauth]
./path/path.c:546: Comparison compare_paths2(const char *, size_t, const char *, size_t): assertion "length1 > 0" failed`
