### ISSUE TITLE
那个第63/62行的https最好改为http，实测https访问不了

### ISSUE THREAD

**Issue by happyabs** [YadominJinta/atilo#91]
63/62     r = requests.get('https://raw.githack.com/YadominJinta/atilo/master/src/list_cn.json')
改成       r = requests.get('http://raw.githack.com/YadominJinta/atilo/master/src/list_cn.json')

我这边似乎没法访问https的，出现 无法连接到GitHub，可能需要代理

**Comment by YadominJinta** [comment]
已经改用国内访问性更好的 https://cdn.jsdeliver.net

**Comment by YadominJinta** [comment]
感谢反馈
