### ISSUE TITLE
Dbus running issue on Fedora distribution

### ISSUE THREAD

**Issue by JanuszChmiel** [YadominJinta/atilo#92]
Please had zou ever been able to run mate or LXDE in Fedora after install it?
dbus-run-session app name
generate The following error
Failed to
  open connection to the audit subsystem: Permission denied

Does DBUS source code also contain some code to communicate with Audit sub system on Debian or Arch Linux? Or The core developers from Redhat have included extra code to The DBUS which want to have extra security and call some Audit sub system which ii specific for Fedora?
because why Arch Linux work smoothly. dbus-run-session appname
do not give errors.
Ubuntu and Debian can even initiate DBUS fully automatic when user type mate-session
for example.
So Why Fedora Dbus is to unsoft for userspace variants of The Fedora OS?

**Comment by YadominJinta** [comment]
You can feedback these issues on fedora mailling list.
Atilo is just a program to help you install linux images, and I don't have the ability to help you solve these systematic problems.

**Comment by JanuszChmiel** [comment]
Unfortunately, Fedora developers do not have A good will to allow users to
install their distros with DBUS support by using Proot.
But I understand, and I Am very sorry that I have intruded you.
