### ISSUE TITLE
ArchLinux can not be correctly installed

### ISSUE THREAD

**Issue by JanuszChmiel** [YadominJinta/atilo#95]
Dear MR Jinta
Arch Linux script is complex and it contain more than setuparch.bash script. Try to git clone The Whole Sdrausty Arch Linux installation package. If you want to successfully incorporate it to yours installer, you must analyse all scripts which are being needed by The main script. And put it together. Warning! It will not be asy work. Setuparch script from MR Rausty really call other Bash script. In other case, ArchLinux will not be installed succesfully.

**Comment by YadominJinta** [comment]
I'm not arch user and I don't what problems will occur in arch. I've seen TermuxArch and I think only the command `pacman-key --init && pacman-key --populate` to fix pacman key error is necessary. Other configs are  aim to fix some specific problem that I don't want to add to this project. Maybe I can open project wiki to give instructions on those problems.

Thank you for using atilo and  keep giving me feedback.
